### ISSUE TITLE
Maybe make schedule posts not viewable on front end

### ISSUE THREAD

**Issue by johnwatkins0** [ivdekov/colby-wp-schedule#1]
This could involve redirecting schedule posts to the homepage and hiding some links on the Edit Schedule page.

**Comment by ivdekov** [comment]
I removed `'public' => true` from schedule's `register_post_type()` args and replaced it with `'show_ui' => true`. This makes it so schedule posts can't be viewed on the front end and if a user attempts to navigate to a schedule's permalink, they are redirected to the site's homepage.

Commit with changes: https://github.com/ivdekov/colby-wp-schedule/commit/bd7c055d215e80a398fec160f4f6809976ed7dfd
